### ISSUE TITLE
Enable/disable on specific notion sites

### ISSUE THREAD

**Issue by jeremychevallier** [creold/open-in-notion#1]
I’d like to use this extension ONLY for my own workspaces (e.g. notion pages I can edit). For other, public notion pages, I’d like to have them open in the browser like any other webpage. 

Therefore, I propose adding whitelist/blacklist options to either:
1. this dialog
![Screen Shot 2020-10-23 at 10 39 00 AM](https://user-images.githubusercontent.com/16313585/97035965-f7c33d80-151b-11eb-802a-5cad94b31895.png)

2. or this section if possible
![Screen Shot 2020-10-23 at 10 39 32 AM](https://user-images.githubusercontent.com/16313585/97036013-0a3d7700-151c-11eb-93dd-7166b6ff31fa.png)

Either way, having the ability to tell the extension “only open these sites in notion, the rest use the browser” would be super useful!

**Comment by creold** [comment]
Hey, Jeremy. I got your donate :-) Thank you. 
I'm not sure how this will work. But I'll think about it later.

**Comment by jeremychevallier** [comment]
Hey! Sorry I don’t check Github notifications often. No sweat though. 

I think the simplest solution would be a setting to:

## Only open in Notion for the following workspaces:
[ enter workspace slug here, e.g. `jeremysworkspace` ] 

Happy to keep brainstorming and even help with UI design if you need! I uninstalled the ext. for now, but am eager to reinstall it :)

**Comment by creold** [comment]
@jeremychevallier check the extension update 0.1.4 in Chrome Web Store. Melvyn Hills made this option for workspaces.

**Comment by jeremychevallier** [comment]
> @jeremychevallier check the extension update 0.1.4 in Chrome Web Store. Melvyn Hills made this option for workspaces.

Works perfectly! @melvynhills, very well done. Next improvement would be a “blacklist” version, for use cases like “I want to open everything in Notion _except_ these workspaces”
